-- Seed 010: catálogo completo de procedimentos (aba "Apoio" do Excel + classificados na fila)
-- Gerado por _tools/_honorarios_seed_procedimentos.py. Rodar DEPOIS de migration_010.
-- Reexecutável: ON CONFLICT pela chave normalizada.

INSERT INTO public.honorarios_procedimentos (chave, procedimento, categoria, origem) VALUES
  ('10 sessoes de fisioterapia', '10 Sessões de fisioterapia', 'Fisioterapia', 'apoio_excel'),
  ('acido alfa lipoico -600mg/24m', 'Ácido Alfa Lipóico -600mg/24m', 'Medicação injetável', 'apoio_excel'),
  ('adek 100 mg', 'Adek 100 MG', 'Medicação injetável', 'apoio_excel'),
  ('aplicacao de hialuronidase', 'Aplicação de Hialuronidase', 'Procedimentos', 'apoio_excel'),
  ('aplicacao de pdrn', 'Aplicação de PDRN', 'Procedimentos', 'apoio_excel'),
  ('avaliacao da composicao corporal por bioimpedanciometria', 'Avaliação da composição corporal por bioimpedanciometria', 'Exames gerais', 'apoio_excel'),
  ('biopsia de pele (por fragmento)', 'Biopsia de Pele (Por fragmento)', 'Procedimentos', 'apoio_excel'),
  ('biopsia excisional', 'Biopsia Excisional', 'Procedimentos', 'apoio_excel'),
  ('botox', 'Botox', 'Procedimentos', 'apoio_excel'),
  ('calorimetria indireta', 'Calorimetria Indireta', 'Exames gerais', 'apoio_excel'),
  ('calorimetria indireta (ambulatorial) exame', 'Calorimetria indireta (ambulatorial) exame', 'Exames gerais', 'apoio_excel'),
  ('cauterizacao quimica (por lesao)', 'Cauterização Química (Por lesão)', 'Procedimentos', 'apoio_excel'),
  ('check-up metabolico', 'Check-up metabólico', 'Consultas', 'apoio_excel'),
  ('cirurgia - aneurisma de aorta abdominal infra-renal', 'Cirurgia - Aneurisma de aorta abdominal infra-renal', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - aneurisma de carotida, subclavia, iliaca', 'Cirurgia - Aneurisma de carótida, subclávia, ilíaca', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - aneurismas - outros', 'Cirurgia - Aneurismas - outros', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - aneurismas toracicos ou toraco-abdominais', 'Cirurgia - Aneurismas torácicos ou tóraco-abdominais', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - angiografia por cateterismo nao seletivo de grande vaso', 'Cirurgia - Angiografia por cateterismo não seletivo de grande vaso', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - angioplastia transluminal percutanea', 'Cirurgia - Angioplastia transluminal percutânea', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - angioplastia transluminal transoperatoria - por arteria', 'Cirurgia - Angioplastia transluminal transoperatória - por artéria', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - colecistite cronica', 'Cirurgia - Colecistite Crônica', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - doppler colorido intra-operatorio', 'Cirurgia - Doppler colorido intra-operatório', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - embolizacao de malformacao vascular - por vaso', 'Cirurgia - Embolização de malformação vascular - por vaso', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - embolizacao de ramos hipogastricos para tratamento de sangramento ginecologico', 'Cirurgia - Embolização de ramos hipogástricos para tratamento de sangramento ginecológico', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - fistula arteriovenosa dos membros', 'Cirurgia - Fístula arteriovenosa dos membros', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - retirada cirurgica de cateter de longa permanencia para npp, qt ou para hemodepuracao', 'Cirurgia - Retirada cirúrgica de cateter de longa permanência para NPP, QT ou para Hemodepuração', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - retirada de chip hormonal', 'Cirurgia - Retirada de Chip Hormonal', 'Cirurgia - Clínica', 'apoio_excel'),
  ('cirurgia - retirada de filtro veia cava', 'Cirurgia - Retirada de filtro veia cava', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - tratamento de ma formacao vascular', 'Cirurgia - Tratamento de Má Formação Vascular', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - varizes - resseccao de colaterais com anestesia local em consultorio / ambulatorio', 'Cirurgia - Varizes - ressecção de colaterais com anestesia local em consultório / ambulatório', 'Cirurgia - Clínica', 'apoio_excel'),
  ('cirurgia - varizes - tratamento cirurgico de dois membros', 'Cirurgia - Varizes - tratamento cirúrgico de dois membros', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - varizes - tratamento cirurgico por radiofrequencia de dois membros', 'Cirurgia - Varizes - tratamento cirúrgico por radiofrequência de dois membros', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia de colecistectomia', 'Cirurgia de Colecistectomia', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia de restauracao venosa com pontes nos membros', 'Cirurgia de restauração venosa com pontes nos membros', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia de unha (1 canto)', 'Cirurgia de Unha (1 Canto)', 'Procedimentos', 'apoio_excel'),
  ('clacs', 'Clacs', 'Procedimentos', 'apoio_excel'),
  ('coenzima q10', 'Coenzima Q10', 'Medicação injetável', 'apoio_excel'),
  ('complexo b - im', 'Complexo B - IM', 'Medicação injetável', 'apoio_excel'),
  ('consulta', 'Consulta', 'Consultas', 'apoio_excel'),
  ('consulta + exames', 'Consulta + Exames', 'Consultas', 'apoio_excel'),
  ('consulta com nutricionista', 'Consulta com Nutricionista', 'Consultas', 'apoio_excel'),
  ('consulta cortesia', 'Consulta Cortesia', 'Consultas', 'apoio_excel'),
  ('consulta em consultorio (no horario normal ou preestabelecido)', 'Consulta em consultório (no horário normal ou preestabelecido)', 'Consultas', 'apoio_excel'),
  ('consulta em dermatologia', 'Consulta em Dermatologia', 'Consultas', 'apoio_excel'),
  ('consulta em fisioterapia', 'Consulta em Fisioterapia', 'Fisioterapia', 'apoio_excel'),
  ('consulta plano', 'Consulta Plano', 'Consultas', 'apoio_excel'),
  ('consulta pos operatoria', 'Consulta pós operatória', 'Consultas', 'apoio_excel'),
  ('consulta pos operatorio', 'Consulta pós operatório', 'Consultas', 'apoio_excel'),
  ('consulta pre operatoria', 'Consulta pré operatória', 'Consultas', 'apoio_excel'),
  ('consulta primeira vez', 'Consulta Primeira Vez', 'Consultas', 'apoio_excel'),
  ('consulta primeira vez + exames', 'Consulta Primeira Vez + Exames', 'Consultas', 'apoio_excel'),
  ('consulta retorno', 'Consulta Retorno', 'Consultas', 'apoio_excel'),
  ('consulta telemedicina', 'Consulta Telemedicina', 'Consultas', 'apoio_excel'),
  ('curativo de extremidades de origem vascular', 'Curativo de extremidades de origem vascular', 'Procedimentos', 'apoio_excel'),
  ('desbridamento cirurgico de feridas ou extremidades', 'Desbridamento cirúrgico de feridas ou extremidades', 'Procedimentos', 'apoio_excel'),
  ('doppler colorido arterial de membro inferior - unilateral', 'Doppler colorido arterial de membro inferior - unilateral', 'Exames de imagem', 'apoio_excel'),
  ('doppler colorido arterial de membro superior - unilateral', 'Doppler colorido arterial de membro superior - unilateral', 'Exames de imagem', 'apoio_excel'),
  ('doppler colorido de aorta e arterias renais', 'Doppler colorido de aorta e artérias renais', 'Exames de imagem', 'apoio_excel'),
  ('doppler colorido de aorta e iliacas', 'Doppler colorido de aorta e ilíacas', 'Exames de imagem', 'apoio_excel'),
  ('doppler colorido de arterias viscerais (mesentericas superior e inferior e tronco celiaco)', 'Doppler colorido de artérias viscerais (mesentéricas superior e inferior e tronco celíaco)', 'Exames de imagem', 'apoio_excel'),
  ('doppler colorido de orgao ou estrutura isolada', 'Doppler colorido de órgão ou estrutura isolada', 'Exames de imagem', 'apoio_excel'),
  ('doppler colorido de vasos cervicais arteriais bilateral (carotidas e vertebrais)', 'Doppler colorido de vasos cervicais arteriais bilateral (carótidas e vertebrais)', 'Exames de imagem', 'apoio_excel'),
  ('doppler colorido de vasos cervicais venosos bilateral (subclavias e jugulares)', 'Doppler colorido de vasos cervicais venosos bilateral (subclávias e jugulares)', 'Exames de imagem', 'apoio_excel'),
  ('doppler colorido de veia cava superior ou inferior', 'Doppler colorido de veia cava superior ou inferior', 'Exames de imagem', 'apoio_excel'),
  ('doppler colorido intra-operatorio', 'Doppler colorido intra-operatório', 'Exames de imagem', 'apoio_excel'),
  ('doppler colorido venoso de membro inferior - unilateral', 'Doppler colorido venoso de membro inferior - unilateral', 'Exames de imagem', 'apoio_excel'),
  ('doppler colorido venoso de membro superior - unilateral', 'Doppler colorido venoso de membro superior - unilateral', 'Exames de imagem', 'apoio_excel'),
  ('dores e inflamacoes - confortlase', 'Dores e Inflamações - ConfortLase', 'Fotona', 'apoio_excel'),
  ('ecg convencional de ate 12 derivacoes', 'ECG convencional de até 12 derivações', 'Exames gerais', 'apoio_excel'),
  ('ecodopplercardiograma transtoracico', 'Ecodopplercardiograma transtorácico', 'Exames de imagem', 'apoio_excel'),
  ('endolaser cirurgico', 'Endolaser Cirúrgico', 'Cirurgia - Hospital', 'apoio_excel'),
  ('endolaser/endolift', 'Endolaser/Endolift', 'Cirurgia - Clínica', 'apoio_excel'),
  ('endolift', 'Endolift', 'Cirurgia - Clínica', 'apoio_excel'),
  ('ergoespirometria ou teste cardiopulmonar de exercicio completo (espirometria forcada, consumo de o2, producao de co2 e derivados, ecg, oximetria)', 'Ergoespirometria ou teste cardiopulmonar de exercício completo (espirometria forçada, consumo de O2, produção de CO2 e derivados, ECG, oximetria)', 'Exames gerais', 'apoio_excel'),
  ('escleroterapia de veias - por sessao', 'Escleroterapia de veias - por sessão', 'Procedimentos', 'apoio_excel'),
  ('espuma', 'Espuma', 'Procedimentos', 'apoio_excel'),
  ('espuma - inativo', 'Espuma - Inativo', 'Procedimentos', 'apoio_excel'),
  ('exerese de nevo (por lesao)', 'Exerese de Nevo (por Lesão)', 'Procedimentos', 'apoio_excel'),
  ('facial', 'Facial', 'Fotona', 'apoio_excel'),
  ('ferinject (1 ampola)', 'Ferinject (1 Ampola)', 'Medicação injetável', 'apoio_excel'),
  ('fio aptos rosto', 'Fio APTOS Rosto', 'Procedimentos', 'apoio_excel'),
  ('fios aptos papada', 'Fios Aptos Papada', 'Procedimentos', 'apoio_excel'),
  ('fotona', 'Fotona', 'Fotona', 'apoio_excel'),
  ('fotona cicatrizes - cicatrizes atroficas', 'Fotona Cicatrizes - Cicatrizes Atróficas', 'Fotona', 'apoio_excel'),
  ('fotona corporal', 'Fotona Corporal', 'Fotona', 'apoio_excel'),
  ('fotona corporal - beauty legs', 'Fotona Corporal - Beauty Legs', 'Fotona', 'apoio_excel'),
  ('fotona corporal - microcoring', 'Fotona Corporal - MicroCoring', 'Fotona', 'apoio_excel'),
  ('fotona corporal - tensortight (areas grandes)', 'Fotona Corporal - TensorTight (Áreas grandes)', 'Fotona', 'apoio_excel'),
  ('fotona corporal - tensortight (areas pequenas)', 'Fotona Corporal - TensorTight (Áreas pequenas)', 'Fotona', 'apoio_excel'),
  ('fotona corporal - thermolipolise', 'Fotona Corporal - ThermoLipólise', 'Fotona', 'apoio_excel'),
  ('fotona corporal - tightsculpting', 'Fotona Corporal - TightSculpting', 'Fotona', 'apoio_excel'),
  ('fotona dores e inflamacoes - fotobiomodulacao', 'Fotona Dores e Inflamações - Fotobiomodulação', 'Fotona', 'apoio_excel'),
  ('fotona embelezamento do olhar - smootheyes', 'Fotona Embelezamento do Olhar - SmoothEyes', 'Fotona', 'apoio_excel'),
  ('fotona faciais - fotona 4d', 'Fotona Faciais - Fotona 4D', 'Fotona', 'apoio_excel'),
  ('fotona faciais - fotona 5d', 'Fotona Faciais - Fotona 5D', 'Fotona', 'apoio_excel'),
  ('fotona faciais - fotona 6d', 'Fotona Faciais - Fotona 6D', 'Fotona', 'apoio_excel'),
  ('fotona faciais - fotona 6d - men', 'Fotona Faciais - Fotona 6D - Men', 'Fotona', 'apoio_excel'),
  ('fotona faciais - veu de noiva', 'Fotona Faciais - Véu de Noiva', 'Fotona', 'apoio_excel'),
  ('fotona full face', 'FOTONA FULL FACE', 'Fotona', 'apoio_excel'),
  ('fotona lesoes benignas - lesoes benignas', 'Fotona Lesões Benignas - Lesões Benignas', 'Fotona', 'apoio_excel'),
  ('fotona onicomicoses', 'Fotona Onicomicoses', 'Fotona', 'apoio_excel'),
  ('fotona saude do sono - nightlase', 'Fotona Saúde do Sono - NightLase', 'Fotona', 'apoio_excel'),
  ('fotona tricologia e remocao de pelos - hairestart', 'Fotona Tricologia e Remoção de Pelos - HairEstart', 'Fotona', 'apoio_excel'),
  ('fotona unhas e verrugas - clearsteps', 'Fotona Unhas e Verrugas - ClearSteps', 'Fotona', 'apoio_excel'),
  ('fotona vascular', 'Fotona Vascular', 'Fotona', 'apoio_excel'),
  ('fotona vasculares - beauty legs', 'Fotona Vasculares - Beauty Legs', 'Fotona', 'apoio_excel'),
  ('fotona vasculares - telangiectasias', 'Fotona Vasculares - Telangiectasias', 'Fotona', 'apoio_excel'),
  ('implante de filtro de veia cava', 'Implante de Filtro de veia Cava', 'Cirurgia - Hospital', 'apoio_excel'),
  ('incisao e drenagem de abscesso, hematoma ou panaricio', 'Incisão e drenagem de abscesso, hematoma ou panarício', 'Procedimentos', 'apoio_excel'),
  ('infiltracao queloide', 'Infiltração Queloide', 'Procedimentos', 'apoio_excel'),
  ('infusao de medicacao - ev', 'Infusão de Medicação - EV', 'Medicação injetável', 'apoio_excel'),
  ('inositol + l-taurina', 'Inositol + L-Taurina', 'Medicação injetável', 'apoio_excel'),
  ('laser dual', 'Laser dual', 'Laser (clínica)', 'apoio_excel'),
  ('laser q-switched', 'Laser Q-Switched', 'Laser (clínica)', 'apoio_excel'),
  ('laser transdermico', 'Laser Transdérmico', 'Laser (clínica)', 'apoio_excel'),
  ('laser tsculptor 2 regioes', 'Laser Tsculptor 2 regiões', 'T-Sculptor', 'apoio_excel'),
  ('laser ultraformer', 'Laser Ultraformer', 'Laser (locação)', 'apoio_excel'),
  ('medicamento diprospan', 'Medicamento Diprospan', 'Medicação injetável', 'apoio_excel'),
  ('meia compleflex sigvari', 'Meia Compleflex Sigvari', 'Produtos', 'apoio_excel'),
  ('meia segretta', 'Meia Segretta', 'Produtos', 'apoio_excel'),
  ('meia select', 'Meia Select', 'Produtos', 'apoio_excel'),
  ('mmp couro cabeludo', 'MMP Couro Cabeludo', 'Procedimentos', 'apoio_excel'),
  ('morpheus', 'Morpheus', 'Cirurgia - Hospital', 'apoio_excel'),
  ('neuromodulacao', 'Neuromodulação', 'Procedimentos', 'apoio_excel'),
  ('noripurum (1 ampola)', 'Noripurum (1 Ampola)', 'Medicação injetável', 'apoio_excel'),
  ('nova consulta', 'Nova Consulta', 'Consultas', 'apoio_excel'),
  ('nova consulta + exames', 'Nova Consulta + Exames', 'Consultas', 'apoio_excel'),
  ('nutri', 'Nutri', 'Consultas', 'apoio_excel'),
  ('peeling acidos', 'Peeling Ácidos', 'Procedimentos', 'apoio_excel'),
  ('pool aminoacidos', 'Pool Aminoácidos', 'Medicação injetável', 'apoio_excel'),
  ('pool de mineirais', 'Pool de Mineirais', 'Medicação injetável', 'apoio_excel'),
  ('preenchimento (por seringa)', 'Preenchimento (Por seringa)', 'Procedimentos', 'apoio_excel'),
  ('primeira vez - apenas consulta', 'Primeira Vez - Apenas Consulta', 'Consultas', 'apoio_excel'),
  ('primeira vez - apenas exames', 'Primeira Vez - Apenas Exames', 'Exames de imagem', 'apoio_excel'),
  ('primeira vez - consulta + exames', 'Primeira Vez - Consulta + Exames', 'Consultas', 'apoio_excel'),
  ('protocolo adjuvante para imunidade - ev', 'Protocolo Adjuvante para Imunidade - EV', 'Medicação injetável', 'apoio_excel'),
  ('protocolo anti-inflamatorio', 'Protocolo Anti-Inflamatório', 'Medicação injetável', 'apoio_excel'),
  ('protocolo antioxidante', 'Protocolo Antioxidante', 'Medicação injetável', 'apoio_excel'),
  ('protocolo pernas de porcelana', 'Protocolo Pernas de Porcelana', 'Cirurgia - Clínica', 'apoio_excel'),
  ('radiofrequencia', 'Radiofrequência', 'Cirurgia - Hospital', 'apoio_excel'),
  ('rejuvenescimento 4d men', 'Rejuvenescimento 4D Men', 'Fotona', 'apoio_excel'),
  ('resveratol', 'Resveratol', 'Medicação injetável', 'apoio_excel'),
  ('riboside', 'Ribosíde', 'Medicação injetável', 'apoio_excel'),
  ('sculptra', 'SCULPTRA', 'Procedimentos', 'apoio_excel'),
  ('sculptra - bioestimulador de colageno - (por frasco)', 'Sculptra - bioestimulador de colageno - (por Frasco)', 'Procedimentos', 'apoio_excel'),
  ('sculptra a partir de 2 frascos', 'Sculptra á partir de 2 frascos', 'Procedimentos', 'apoio_excel'),
  ('sedacao consciente com oxido nitroso', 'Sedação Consciente com Óxido Nitroso', 'Procedimentos', 'apoio_excel'),
  ('sessao de espuma para varizes', 'Sessão de Espuma para Varizes', 'Procedimentos', 'apoio_excel'),
  ('sessao de fisioterapia', 'Sessão de Fisioterapia', 'Fisioterapia', 'apoio_excel'),
  ('sinal de consulta', 'Sinal de Consulta', 'Consultas', 'apoio_excel'),
  ('skinbooster', 'Skinbooster', 'Procedimentos', 'apoio_excel'),
  ('taxa de aplicacao de injecao im', 'Taxa de Aplicação de Injeção IM', 'Medicação injetável', 'apoio_excel'),
  ('toxina botulinica', 'Toxina Botulínica', 'Procedimentos', 'apoio_excel'),
  ('t-sculptor - 8 sessoes (1 area)', 'T-SCULPTOR - 8 Sessões (1 área)', 'T-Sculptor', 'apoio_excel'),
  ('t-sculptor - 8 sessoes (2 areas)', 'T-SCULPTOR - 8 Sessões (2 áreas)', 'T-Sculptor', 'apoio_excel'),
  ('t-sculptor - sessao individual (1 area)', 'T-SCULPTOR - Sessão Individual (1 área)', 'T-Sculptor', 'apoio_excel'),
  ('varizes - resseccao de colaterais com anestesia local em consultorio / ambulatorio', 'Varizes - ressecção de colaterais com anestesia local em consultório / ambulatório', 'Cirurgia - Clínica', 'apoio_excel'),
  ('varizes - tratamento cirurgico de dois membros', 'Varizes - tratamento cirúrgico de dois membros', 'Cirurgia - Hospital', 'apoio_excel'),
  ('vasculares - beauty legs', 'Vasculares - Beauty Legs', 'Fotona', 'apoio_excel'),
  ('vasculares - telangiectasias', 'Vasculares - Telangiectasias', 'Fotona', 'apoio_excel'),
  ('vitamina b12 2500mg', 'Vitamina B12 2500mg', 'Medicação injetável', 'apoio_excel'),
  ('vitamina b12 5000mg', 'Vitamina B12 5000mg', 'Medicação injetável', 'apoio_excel'),
  ('vitamina d 100.000mg', 'Vitamina D 100.000mg', 'Medicação injetável', 'apoio_excel'),
  ('sessao de espuma para safena', 'Sessão de Espuma para Safena', 'Procedimentos', 'apoio_excel'),
  ('cirurgia - embolizacao de veias ovarianas para tratamento de varizes pelvicas', 'Cirurgia - Embolização de veias ovarianas para tratamento de varizes pélvicas', 'Cirurgia - Hospital', 'apoio_excel'),
  ('angiografia por cateterismo superseletivo de ramo secundario ou distal - por vaso', 'Angiografia por cateterismo superseletivo de ramo secundário ou distal - por vaso', 'Cirurgia - Hospital', 'apoio_excel'),
  ('cirurgia - esofagectomia subtotal com linfadenectomia com ou sem toracotomia', 'Cirurgia - Esofagectomia subtotal com linfadenectomia com ou sem toracotomia', 'Cirurgia - Hospital', 'apoio_excel'),
  ('infusao de medicacao - im', 'Infusão de Medicação - IM', 'Medicação injetável', 'apoio_excel'),
  ('vitamina d 100.000ui', 'Vitamina D 100.000UI', 'Medicação injetável', 'apoio_excel'),
  ('cirurgia - angiografia por cateterismo superseletivo de ramo secundario ou distal - por vaso', 'Cirurgia - Angiografia por cateterismo superseletivo de ramo secundário ou distal - por vaso', 'Cirurgia - Hospital', 'apoio_excel'),
  ('fotona corporal - linelase', 'Fotona Corporal - LineLase', 'Fotona', 'apoio_excel'),
  ('subcisao - corpo', 'Subcisão - Corpo', 'Procedimentos', 'apoio_excel'),
  ('trombolise medicamentosa arterial ou venosa - por vaso', 'Trombólise medicamentosa arterial ou venosa - por vaso', 'Cirurgia - Hospital', 'apoio_excel'),
  ('custos de cirurgia em outro estado', 'Custos de cirurgia em outro estado', 'Cirurgia - Hospital', 'apoio_excel'),
  ('morpheus - clinica', 'Morpheus - Clínica', 'Cirurgia - Clínica', 'apoio_excel'),
  ('visita hospitalar (paciente internado)', 'Visita hospitalar (paciente internado)', 'Cirurgia - Hospital', 'apoio_excel'),
  ('vitamina d 50.000mg', 'Vitamina D 50.000mg', 'Medicação injetável', 'apoio_excel'),
  ('cirurgia - tenotomia', 'Cirurgia - Tenotomia', 'Cirurgia - Hospital', 'apoio_excel'),
  ('preenchimento (por seringa) - tabela diretoria', 'Preenchimento (Por seringa) - Tabela Diretoria', 'Procedimentos', 'apoio_excel'),
  ('exossomos - terapia regenerativa', 'Exossomos - Terapia Regenerativa', 'Procedimentos', 'apoio_excel'),
  ('hybrius evo - sessao individual (1 area)', 'Hybrius EVO - Sessão individual (1 área)', 'Laser (clínica)', 'apoio_excel'),
  ('exerese e sutura simples de pequenas lesoes (por grupo de ate 5 lesoes)', 'Exérese e sutura simples de pequenas lesões (por grupo de até 5 lesões)', 'Procedimentos', 'apoio_excel'),
  ('taxa compacta de sala de pequenas cirurgias', 'Taxa compacta de sala de pequenas cirurgias', 'Cirurgia - Clínica', 'apoio_excel')
ON CONFLICT (chave) DO UPDATE SET categoria = EXCLUDED.categoria;

-- Conferência:
-- SELECT categoria, count(*) FROM public.honorarios_procedimentos
--  GROUP BY categoria ORDER BY categoria;
